-- MySQL Script generated by MySQL Workbench
-- Fri Nov 23 13:57:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GLANCE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GLANCE` ;

-- -----------------------------------------------------
-- Schema GLANCE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GLANCE` DEFAULT CHARACTER SET utf8 ;
USE `GLANCE` ;

-- -----------------------------------------------------
-- Table `GLANCE`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GLANCE`.`USERS` ;

CREATE TABLE IF NOT EXISTS `GLANCE`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `background` INT NOT NULL,
  `contact` CHAR(1) NOT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `GLANCE`.`PLATOONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GLANCE`.`PLATOONS` ;

CREATE TABLE IF NOT EXISTS `GLANCE`.`PLATOONS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `GLANCE`.`MESSAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GLANCE`.`MESSAGES` ;

CREATE TABLE IF NOT EXISTS `GLANCE`.`MESSAGES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `message` VARCHAR(250) NOT NULL,
  `platoonID` INT NOT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `GLANCE`.`SUBSCRIBERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GLANCE`.`SUBSCRIBERS` ;

CREATE TABLE IF NOT EXISTS `GLANCE`.`SUBSCRIBERS` (
  `ID` INT NOT NULL,
  `userID` INT NOT NULL,
  `platoonID` INT NOT NULL,
  `authorized` ENUM('yes', 'no') NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `GLANCE`.`WATCH_BYS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GLANCE`.`WATCH_BYS` ;

CREATE TABLE IF NOT EXISTS `GLANCE`.`WATCH_BYS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `platoonID` INT NOT NULL,
  `url` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `GLANCE`.`FAVORITES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GLANCE`.`FAVORITES` ;

CREATE TABLE IF NOT EXISTS `GLANCE`.`FAVORITES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `urlID` INT NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `GLANCE`.`CATEGORYS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GLANCE`.`CATEGORYS` ;

CREATE TABLE IF NOT EXISTS `GLANCE`.`CATEGORYS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `GLANCE`.`BELONGS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GLANCE`.`BELONGS` ;

CREATE TABLE IF NOT EXISTS `GLANCE`.`BELONGS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoryID` INT NOT NULL,
  `platoonID` INT NOT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
